// ============================================================
// DESCRIPCIONES DE PRODUCTOS — POWERX
// Edita solo el campo 'descripcion' de cada producto.
// Deja en blanco ('') los que no tengan descripción todavía.
// ============================================================

const descripciones = [
  { nombre: "43 BCAA + GLUTAMINA", descripcion: "Fórmula que combina BCAA y Glutamina para reconstrucción muscular completa. Favorece síntesis de proteína, previene catabolismo muscular y preserva el glucógeno. Mejora rendimiento aeróbico y anaeróbico. Reduce dolor muscular post-entrenamiento. 75 servicios." },
  { nombre: "43 GAINER", descripcion: "Fórmula hipercalórica con proteína, carbohidratos y micronutrientes para incrementar peso y volumen muscular de forma efectiva." },
  { nombre: "43 RODILLERAS", descripcion: "De alta calidad para soporte y protección de rodillas durante el entrenamiento con pesas y ejercicios de alta intensidad." },
  { nombre: "43 WHEY COSTAL", descripcion: "22g de proteína de suero por servicio. 2 kg / 84 servicios. Ideal para desarrollo muscular a precio accesible." },
  { nombre: "43 ZERO 10 KG", descripcion: "Zero Carb. 30 g de proteína por servicio, cero carbohidratos. Máxima eficiencia proteica. 10 kg / 312 servicios." },
  { nombre: "43 ZERO 2.4 KG", descripcion: "Zero Carb. 30 g de proteína por servicio, cero carbohidratos, sin azúcares añadidos. 2.4 kg / 76 servicios." },
  { nombre: "43 ZERO 5 KG MULTISABOR", descripcion: "Proteína 43 Zero multisabor. Bolsitas de 1 kg en sabores: chocolate, fresa, vainilla y más. 30 g proteína, 0 carbohidratos. 150 servicios." },
  { nombre: "43 ZERO 6 KG", descripcion: "Zero Carb. 30 g de proteína por servicio, cero carbohidratos. 6 kg / 187 servicios. Económica y de alta calidad." },
  { nombre: "ACXION", descripcion: "Mejora tu cuerpo. Controla tu ingesta calórica. Controla tu apetito." },
  { nombre: "AMINO ENERGY ON CHICO", descripcion: "5 g de Aminoácidos Esenciales (EAA) con BCAA Leucina, Isoleucina y Valina. Cafeína ajustable. Para desarrollo y recuperación muscular. 30 servicios." },
  { nombre: "AMINO ENERGY ON GRANDE", descripcion: "5 g de EAA con BCAA. Cafeína ajustable para personalizar tu energía en cualquier entrenamiento. 65 servicios." },
  { nombre: "AMINO X CHICO", descripcion: "libre de estimulantes con 10 g de BCAA + L-Alanina, Taurina y L-Citrulina. Apoya resistencia durante el entreno y recuperación muscular post-ejercicio. 30 servicios." },
  { nombre: "AMINO X GRANDE", descripcion: "libre de estimulantes con 10 g de BCAA + L-Alanina, Taurina y L-Citrulina. Soporte nutricional versátil para cualquier régimen. 70 servicios." },
  { nombre: "AMINOJECT", descripcion: "6 g de BCAA fermentados por servicio. Estimula síntesis proteica y detiene procesos catabólicos. Contiene Glutamina y Betaína para recuperación ultrarrápida. 30 servicios." },
  { nombre: "ANGUS MASS", descripcion: "Ganador de masa con proteína y carbohidratos para incremento de volumen y fuerza muscular. Ideal para personas con metabolismo acelerado." },
  { nombre: "ANIMAL FLEX", descripcion: "6 g de BCAA fermentados por servicio. Estimula síntesis proteica y detiene procesos catabólicos. Contiene Glutamina y Betaína para recuperación ultrarrápida. 30 servicios." },
  { nombre: "ANIMAL PACK", descripcion: "Multivitamínico completo en paquete. Vitaminas, minerales, antioxidantes y ácidos grasos esenciales. El suplemento más completo para el" },
  { nombre: "B NOVA BCAA", descripcion: " 2:1:1 para construcción y mantenimiento muscular. Previene catabolismo durante entrenamientos intensos. Energía rápida durante el entreno. Reduce dolor muscular y acelera reparación de fibras. 50 servicios" },
  { nombre: "B NOVA CREATINA CHICA", descripcion: "El compuesto más estudiado del fitness. Mejora rendimiento en actividades de alta intensidad y corta duración. 100 servicios." },
  { nombre: "B NOVA CREATINA GRANDE", descripcion: "de alta pureza y biodisponibilidad. Mejora rendimiento en actividades de alta intensidad y corta duración. 200 servicios." },
  { nombre: "B NOVA ISO FEMME 1 KG", descripcion: "Proteína hidrolizada B Nova para mujer. Formulada con Colágeno Hidrolizado para piel, cabello y uñas, Ácido Fólico y L-Carnitina para metabolismo de grasas. 33 servicios." },
  { nombre: "B NOVA PEPTONAS", descripcion: "péptidos proteicos de alta asimilación para recuperación acelerada y síntesis proteica optimizada." },
  { nombre: "B NOVA ZERO 1 KG", descripcion: "Proteína Zero Hidrolizada B Nova — 28 g proteína, 5 g BCAA, 0 g carbohidratos. Rápida absorción y sin azúcares. Perfecta para etapas de definición o control de peso. 33 servicios." },
  { nombre: "B NOVA ZERO 4.5 KG", descripcion: "Proteína Zero Hidrolizada B Nova — 28 g proteína, 5 g BCAA, 0 g carbohidratos. Para equilibrio, energía, rendimiento y bienestar. 150 servicios." },
  { nombre: "BCAA MUTANT", descripcion: "" },
  { nombre: "BCAA SUPREME", descripcion: "" },
  { nombre: "BETA ALANINA GAT", descripcion: "" },
  { nombre: "BHP WHEY ULTRA", descripcion: "" },
  { nombre: "BLACK SPIDER", descripcion: "" },
  { nombre: "BLIFE 3 MAG BLEND", descripcion: "" },
  { nombre: "BLIFE 80 BILLION PROBIOTIC", descripcion: "" },
  { nombre: "BLIFE ACIDO ALFA LIPOICO", descripcion: "" },
  { nombre: "BLIFE ASHWAGANDA", descripcion: "" },
  { nombre: "BLIFE B YEAST BLEND", descripcion: "" },
  { nombre: "BLIFE BOTELLA CON FUNDA", descripcion: "" },
  { nombre: "BLIFE BOTELLA CON TOALLA", descripcion: "" },
  { nombre: "BLIFE BOTELLA TÉRMICA", descripcion: "" },
  { nombre: "BLIFE CALCIO+D3", descripcion: "" },
  { nombre: "BLIFE CALOSTRO BOVINO", descripcion: "" },
  { nombre: "BLIFE CITRATO DE MAGNESIO CHICO", descripcion: "" },
  { nombre: "BLIFE CITRATO DE MAGNESIO GRANDE", descripcion: "" },
  { nombre: "BLIFE CITRATO DE POTASIO", descripcion: "" },
  { nombre: "BLIFE COLAGENO BIO", descripcion: "" },
  { nombre: "BLIFE COLAGENO BLEND", descripcion: "" },
  { nombre: "BLIFE CREATINA", descripcion: "" },
  { nombre: "BLIFE D3 PLUS", descripcion: "" },
  { nombre: "BLIFE ELECTRO BLEND + CREATINA", descripcion: "" },
  { nombre: "BLIFE GLICINATO DE MAGNESIO", descripcion: "" },
  { nombre: "BLIFE JOINT BLEND", descripcion: "" },
  { nombre: "BLIFE KIT TOALLAS", descripcion: "" },
  { nombre: "BLIFE MACA BLEND", descripcion: "" },
  { nombre: "BLIFE MENS BLEND", descripcion: "" },
  { nombre: "BLIFE MENS T PLATINUM", descripcion: "" },
  { nombre: "BLIFE MYO INOSITOL", descripcion: "" },
  { nombre: "BLIFE OMEGA 3 CHICO", descripcion: "" },
  { nombre: "BLIFE OMEGA 3 GRANDE", descripcion: "" },
  { nombre: "BLIFE RESVERATROL", descripcion: "" },
  { nombre: "BLIFE TRIBULUS", descripcion: "" },
  { nombre: "BLIFE VITAMINA E+BIOTINA", descripcion: "" },
  { nombre: "BLIFE WOMENS BLEND", descripcion: "" },
  { nombre: "C4 ORIGINAL CHICO", descripcion: "" },
  { nombre: "C4 ORIGINAL GRANDE", descripcion: "" },
  { nombre: "CAFEINA GAT", descripcion: "" },
  { nombre: "CAFEINA MUTANT", descripcion: "" },
  { nombre: "CARBOTEIN", descripcion: "" },
  { nombre: "CARNIVOR BOTE", descripcion: "" },
  { nombre: "CARNIVOR MASS", descripcion: "" },
  { nombre: "CBUM ESSENTIAL CHICO", descripcion: "" },
  { nombre: "CBUM ITHOLATE CHICA", descripcion: "" },
  { nombre: "CBUM ITHOLATE GRANDE", descripcion: "" },
  { nombre: "CELL TECH 3 LBS", descripcion: "" },
  { nombre: "CELL TECH 6LBS", descripcion: "" },
  { nombre: "CELL TECH CREACTOR", descripcion: "" },
  { nombre: "CINTURON", descripcion: "" },
  { nombre: "CITRULINA ADVANCED", descripcion: "" },
  { nombre: "CITRULINA INSANE", descripcion: "" },
  { nombre: "CLA 1250 GAT", descripcion: "" },
  { nombre: "CLA+CARNITINA BPI", descripcion: "" },
  { nombre: "COFFEE MAX", descripcion: "" },
  { nombre: "COLÁGENO HIDROLIZADO SHE FIT", descripcion: "" },
  { nombre: "COLÁGENO META", descripcion: "" },
  { nombre: "CREATINA BIRDMAN", descripcion: "" },
  { nombre: "CREATINA CELLUCOR", descripcion: "" },
  { nombre: "CREATINA CREAKON CX8", descripcion: "" },
  { nombre: "CREATINA DRAGON CHICA", descripcion: "" },
  { nombre: "CREATINA DRAGON GRANDE", descripcion: "" },
  { nombre: "CREATINA ELECTROLYTE", descripcion: "" },
  { nombre: "CREATINA GAT CHICA", descripcion: "" },
  { nombre: "CREATINA GAT GRANDE", descripcion: "" },
  { nombre: "CREATINA HI TECH CHICA", descripcion: "" },
  { nombre: "CREATINA HI TECH GRANDE", descripcion: "" },
  { nombre: "CREATINA INSANE", descripcion: "" },
  { nombre: "CREATINA META", descripcion: "" },
  { nombre: "CREATINA NUTREX CHICA", descripcion: "" },
  { nombre: "CREATINA NUTREX GRANDE", descripcion: "" },
  { nombre: "CREATINA ON", descripcion: "" },
  { nombre: "CREATINA PLATINUM", descripcion: "" },
  { nombre: "CREATINA RC CHICA", descripcion: "" },
  { nombre: "CREATINA RC GRANDE", descripcion: "" },
  { nombre: "CREATINA ULTRA BHP 300 GRS", descripcion: "" },
  { nombre: "CREATINA ULTRA BHP 500 GRS", descripcion: "" },
  { nombre: "DEFIT CREATINA CHICA", descripcion: "" },
  { nombre: "DEFIT CREATINA GRANDE", descripcion: "" },
  { nombre: "DEFIT FIT FEMME", descripcion: "" },
  { nombre: "DEFIT ISOLATE WHEY CHICA", descripcion: "" },
  { nombre: "DEFIT ISOLATE WHEY GRANDE", descripcion: "" },
  { nombre: "DEFIT PEPTONAS", descripcion: "" },
  { nombre: "DEMON BCAA", descripcion: "" },
  { nombre: "DEMON DUST", descripcion: "" },
  { nombre: "ELITE WHEY 5 LBS", descripcion: "" },
  { nombre: "EVP 3D", descripcion: "" },
  { nombre: "EVP XTREME", descripcion: "" },
  { nombre: "FALCON PERFORMANCE", descripcion: "" },
  { nombre: "FARMACOLOGIA ROTTERDAM", descripcion: "" },
  { nombre: "FARMACOLOGIA SYNTEX LABS", descripcion: "" },
  { nombre: "FARMACOLOGIA XT LABS", descripcion: "" },
  { nombre: "FITMINGO", descripcion: "" },
  { nombre: "FLEXX EAAS", descripcion: "" },
  { nombre: "GAINER ULTRA", descripcion: "" },
  { nombre: "GHOST LEGEND PWO", descripcion: "" },
  { nombre: "GHOST WHEY 2 LBS", descripcion: "" },
  { nombre: "GLUTAMINA PURE CHICA", descripcion: "" },
  { nombre: "GLUTAMINA PURE GRANDE", descripcion: "" },
  { nombre: "GLUTAMINA GAT", descripcion: "" },
  { nombre: "GLUTAMINA MUTANT", descripcion: "" },
  { nombre: "GLUTAMINA PLATINUM", descripcion: "" },
  { nombre: "GOLD STANDARD 10 LBS", descripcion: "" },
  { nombre: "GOLD STANDARD 2 LBS", descripcion: "" },
  { nombre: "GOLD STANDARD 5 LBS", descripcion: "" },
  { nombre: "GOLD STANDARD ISOLATE", descripcion: "" },
  { nombre: "HYDROTEIN", descripcion: "" },
  { nombre: "HYDROXYCUT HARDCORE ELITE", descripcion: "" },
  { nombre: "INSANE VEINZ", descripcion: "" },
  { nombre: "ISOPHORM", descripcion: "" },
  { nombre: "ISO 100 1.3 LBS", descripcion: "" },
  { nombre: "ISO 100 3 LBS", descripcion: "" },
  { nombre: "ISO 100 5 LBS", descripcion: "" },
  { nombre: "ISOFIT", descripcion: "" },
  { nombre: "ISOPURE", descripcion: "" },
  { nombre: "JOINT SUPPORT GAT", descripcion: "" },
  { nombre: "L ARGININA GAT", descripcion: "" },
  { nombre: "L CARNITINA GAT CAPS", descripcion: "" },
  { nombre: "L CARNITINA ULTRA LIQUIDA", descripcion: "" },
  { nombre: "LIPO 6 BLACK HERS 60 CAPS", descripcion: "" },
  { nombre: "LIPO 6 BLACK ROJO 120 CAPS", descripcion: "" },
  { nombre: "LIPODRENE AMARILLO", descripcion: "" },
  { nombre: "LIPODRENE NEGRO", descripcion: "" },
  { nombre: "LIPODRENE VERDE", descripcion: "" },
  { nombre: "MADNESS MUTANT", descripcion: "" },
  { nombre: "MAGNESIO BHP CAPS", descripcion: "" },
  { nombre: "MASS TECH EXTREME 2000", descripcion: "" },
  { nombre: "MESOFRANCE ANTIOBESIDAD", descripcion: "" },
  { nombre: "MESOFRANCE LIPOENZIMAS", descripcion: "" },
  { nombre: "MESOFRANCE PEPTONAS", descripcion: "" },
  { nombre: "MESOFRANCE REDUGRASS", descripcion: "" },
  { nombre: "MULTI VITAMIN + TEST CHICO", descripcion: "" },
  { nombre: "MULTI VITAMIN + TEST GRANDE", descripcion: "" },
  { nombre: "MULTIVITAMINICO PLATINUM", descripcion: "" },
  { nombre: "MUTANT MASS CHICO", descripcion: "" },
  { nombre: "MUTANT MASS GRANDE", descripcion: "" },
  { nombre: "MUTANT WHEY 10 LBS", descripcion: "" },
  { nombre: "MUTANT WHEY 5 LBS", descripcion: "" },
  { nombre: "MUTANT WHEY DUAL", descripcion: "" },
  { nombre: "NITRAFLEX", descripcion: "" },
  { nombre: "NITRO TECH PERFORMANCE 4 LBS", descripcion: "" },
  { nombre: "NITRO TECH WHEY GOLD 2 LBS", descripcion: "" },
  { nombre: "NITRO TECH WHEY GOLD 5 LBS", descripcion: "" },
  { nombre: "NITROTECH RIPPED 4 LBS", descripcion: "" },
  { nombre: "OMEGA 3 GAT", descripcion: "" },
  { nombre: "OPTI MEN", descripcion: "" },
  { nombre: "OPTI WOMEN", descripcion: "" },
  { nombre: "PHANTOM XS", descripcion: "" },
  { nombre: "PSYCHOTIC DORADO", descripcion: "" },
  { nombre: "PSYCHOTIC NEGRO", descripcion: "" },
  { nombre: "PSYCHOTIC ROJO CHICO", descripcion: "" },
  { nombre: "PSYCHOTIC ROJO GRANDE", descripcion: "" },
  { nombre: "PSYCHOTIC SAW", descripcion: "" },
  { nombre: "PSYCHOTIC SOBRES NEGRO", descripcion: "" },
  { nombre: "PSYCHOTIC SOBRES ROJO", descripcion: "" },
  { nombre: "PYSCHOTIC SOBRES DORADO", descripcion: "" },
  { nombre: "REYKON CREATINA GRANDE", descripcion: "" },
  { nombre: "REYKON PRIMATE BURST", descripcion: "" },
  { nombre: "REYKON ZERO 1 KG", descripcion: "" },
  { nombre: "REYKON ZERO 10 KG", descripcion: "" },
  { nombre: "REYKON ZERO 6 KG", descripcion: "" },
  { nombre: "REYKON ZERO MULTISABOR", descripcion: "" },
  { nombre: "RONNIE WHEY XS", descripcion: "" },
  { nombre: "RYSE LOADED PRE", descripcion: "" },
  { nombre: "SERIOUS MASS CHICO", descripcion: "" },
  { nombre: "SERIOUS MASS GRANDE", descripcion: "" },
  { nombre: "SHAKER COLOR LISO", descripcion: "" },
  { nombre: "SHAKER SYNTRAX", descripcion: "" },
  { nombre: "SHAKER GARRAFON", descripcion: "" },
  { nombre: "STRAPS (CAYERAS)", descripcion: "" },
  { nombre: "SUPER PUMP MAX", descripcion: "" },
  { nombre: "SYNTHA 6", descripcion: "" },
  { nombre: "TESTROL GOLD", descripcion: "" },
  { nombre: "TESTROL ORIGINAL", descripcion: "" },
  { nombre: "THE CURSE", descripcion: "" },
  { nombre: "TOTAL WAR", descripcion: "" },
  { nombre: "VAPOR X", descripcion: "" },
  { nombre: "VEGAN NATURALS", descripcion: "" },
  { nombre: "VENOM INFERNO", descripcion: "" },
  { nombre: "VITAMINA C INSANE", descripcion: "" },
  { nombre: "WHEY HD", descripcion: "" },
  { nombre: "XTINCTION MULTISABOR", descripcion: "" },
  { nombre: "YOHIMBINE", descripcion: "" },
  { nombre: "ZMAG GAT", descripcion: "" },
];